export const mockRegions: RegionData[] = [
    {
        name: "São Paulo",
        areaKm2: 1521,
        burnedOccurrences: 12,
        indicators: {
            queimadas: true,
            terrasIndigenas: false,
            unidadesConservacao: true,
            quilombolas: false,
            assentamentos: true,
        },
        score: 72,
        risk: "medio",
    },
    {
        name: "Campinas",
        areaKm2: 795,
        burnedOccurrences: 5,
        indicators: {
            queimadas: true,
            terrasIndigenas: false,
            unidadesConservacao: false,
            quilombolas: false,
            assentamentos: true,
        },
        score: 65,
        risk: "medio",
    },
    {
        name: "Santos",
        areaKm2: 280,
        burnedOccurrences: 2,
        indicators: {
            queimadas: false,
            terrasIndigenas: false,
            unidadesConservacao: true,
            quilombolas: false,
            assentamentos: false,
        },
        score: 88,
        risk: "baixo",
    },
    {
        name: "Ribeirão Preto",
        areaKm2: 650,
        burnedOccurrences: 20,
        indicators: {
            queimadas: true,
            terrasIndigenas: false,
            unidadesConservacao: false,
            quilombolas: false,
            assentamentos: true,
        },
        score: 40,
        risk: "alto",
    },
    {
        name: "Sorocaba",
        areaKm2: 450,
        burnedOccurrences: 8,
        indicators: {
            queimadas: true,
            terrasIndigenas: false,
            unidadesConservacao: true,
            quilombolas: false,
            assentamentos: false,
        },
        score: 60,
        risk: "medio",
    },
    {
        name: "São José dos Campos",
        areaKm2: 1100,
        burnedOccurrences: 3,
        indicators: {
            queimadas: false,
            terrasIndigenas: false,
            unidadesConservacao: true,
            quilombolas: false,
            assentamentos: false,
        },
        score: 82,
        risk: "baixo",
    },
    {
        name: "Bauru",
        areaKm2: 667,
        burnedOccurrences: 14,
        indicators: {
            queimadas: true,
            terrasIndigenas: false,
            unidadesConservacao: false,
            quilombolas: false,
            assentamentos: true,
        },
        score: 55,
        risk: "medio",
    },
    {
        name: "Osasco",
        areaKm2: 64,
        burnedOccurrences: 1,
        indicators: {
            queimadas: false,
            terrasIndigenas: false,
            unidadesConservacao: false,
            quilombolas: false,
            assentamentos: false,
        },
        score: 90,
        risk: "baixo",
    },
    {
        name: "Guarulhos",
        areaKm2: 318,
        burnedOccurrences: 6,
        indicators: {
            queimadas: true,
            terrasIndigenas: false,
            unidadesConservacao: false,
            quilombolas: false,
            assentamentos: true,
        },
        score: 58,
        risk: "medio",
    },
    {
        name: "Mogi das Cruzes",
        areaKm2: 712,
        burnedOccurrences: 4,
        indicators: {
            queimadas: false,
            terrasIndigenas: false,
            unidadesConservacao: true,
            quilombolas: false,
            assentamentos: false,
        },
        score: 78,
        risk: "baixo",
    },
    {
        name: "São Bernardo do Campo",
        areaKm2: 409,
        burnedOccurrences: 7,
        indicators: {
            queimadas: true,
            terrasIndigenas: false,
            unidadesConservacao: true,
            quilombolas: false,
            assentamentos: false,
        },
        score: 62,
        risk: "medio",
    },
    {
        name: "Santo André",
        areaKm2: 175,
        burnedOccurrences: 3,
        indicators: {
            queimadas: false,
            terrasIndigenas: false,
            unidadesConservacao: true,
            quilombolas: false,
            assentamentos: false,
        },
        score: 85,
        risk: "baixo",
    },
];